# Copyright (c) 2025, Sergey Gunin
# Released under the MIT license (see LICENSE for the terms)

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hikrobot"
BBFILE_PATTERN_hikrobot := "^${LAYERDIR}/"
BBFILE_PRIORITY_hikrobot = "10"

# Depends from layers
LAYERDEPENDS_hikrobot = "core openembedded-layer"

# This should only be incremented on significant changes that will
# # cause compatibility issues with other layers
LAYERVERSION_hikrobot = "1"
LAYERSERIES_COMPAT_hikrobot = "kirkstone nanbield scarthgap styhead"

# Additional license directories
LICENSE_PATH += "${LAYERDIR}/licenses"

# Add require recipie to image
IMAGE_INSTALL:append = " \
	hikrobot-sdk \
	udev-hikrobot \
"
